### ISSUE TITLE
Unknown parameter in input: "ElasticsearchVersion"

### ISSUE THREAD

**Issue by akabdog** [fiunchinho/ansible-aws-elasticsearch-module#9]
Perhaps something with the aws sdk changed but I wasn't able to get this module to work for me.

```An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_xGoIah/ansible_module_ec2_elasticsearch.py", line 239, in <module>
    main()
  File "/tmp/ansible_xGoIah/ansible_module_ec2_elasticsearch.py", line 225, in main
    AccessPolicies=pdoc,
  File "/home/bsmith01/.local/lib/python2.7/site-packages/botocore/client.py", line 228, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/bsmith01/.local/lib/python2.7/site-packages/botocore/client.py", line 468, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/bsmith01/.local/lib/python2.7/site-packages/botocore/client.py", line 521, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/bsmith01/.local/lib/python2.7/site-packages/botocore/validate.py", line 269, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "ElasticsearchVersion", must be one of: DomainName, ElasticsearchClusterConfig, EBSOptions, AccessPolicies, SnapshotOptions, AdvancedOptions
```

Here is my config:
```
- name: "Create ElasticSearch cluster"
  ec2_elasticsearch:
    name: "my-cluster-test"
    elasticsearch_version: "2.3"
    region: "us-east-1"
    instance_type: "t2.small.elasticsearch"
    instance_count: "3"
    zone_awareness: False
    dedicated_master: False
    ebs: True
    volume_type: "gp2"
    volume_size: 50
    snapshot_hour: 13
    access_policies: "{{ lookup('template', playbook_dir + '/roles/retraced/templates/elasticsearch_iam.yml.j2') }}"
    profile: "default"
  register: response
```

thanks!

**Comment by akabdog** [comment]
An upgrade of boto3 and botocore seems to have fixed this, closing, thanks for a great module!
